planning_scope: worktree
profile: development.standard
protocol: adp/1
protocols: git+https://github.com/beyond10x/aep.git#733dbea25c8db9e5a0b7d273c09c287db60bfac2
store:
  git: {}
version: aep.project/5
