//! `worktree skill` prints the skill unless an output directory is named.

use std::process::Command;

fn entries(path: &std::path::Path) -> Vec<std::path::PathBuf> {
    std::fs::read_dir(path)
        .expect("read working directory")
        .map(|entry| entry.expect("directory entry").path())
        .collect()
}

#[test]
fn skill_without_out_prints_the_skill_and_writes_no_file() {
    let working = tempfile::tempdir().expect("temporary working directory");
    let output = Command::new(env!("CARGO_BIN_EXE_worktree"))
        .arg("skill")
        .current_dir(working.path())
        .output()
        .expect("run worktree CLI");

    assert!(output.status.success());
    assert_eq!(output.stderr, [] as [u8; 0]);
    let stdout = String::from_utf8(output.stdout).expect("UTF-8 stdout");
    assert!(stdout.starts_with("---\nname: worktree\n"));
    assert!(stdout.contains("Generated by `worktree skill`"));
    assert_eq!(entries(working.path()), Vec::<std::path::PathBuf>::new());
}

#[test]
fn skill_json_without_out_is_refused_and_writes_no_file() {
    let working = tempfile::tempdir().expect("temporary working directory");
    let output = Command::new(env!("CARGO_BIN_EXE_worktree"))
        .args(["--json", "skill"])
        .current_dir(working.path())
        .output()
        .expect("run worktree CLI");

    assert!(!output.status.success());
    assert_eq!(output.stdout, [] as [u8; 0]);
    let stderr = String::from_utf8(output.stderr).expect("UTF-8 stderr");
    let value: serde_json::Value = serde_json::from_str(stderr.trim()).expect("one JSON document");
    assert_eq!(value["version"], 4);
    assert_eq!(value["ok"], false);
    assert_eq!(value["code"], "operation-failed");
    assert!(value["message"].as_str().unwrap().contains("--out"));
    assert_eq!(entries(working.path()), Vec::<std::path::PathBuf>::new());
}

#[test]
fn skill_with_out_writes_the_skill_and_its_interface() {
    let working = tempfile::tempdir().expect("temporary working directory");
    let output = Command::new(env!("CARGO_BIN_EXE_worktree"))
        .args(["skill", "--out", "rendered"])
        .current_dir(working.path())
        .output()
        .expect("run worktree CLI");

    assert!(output.status.success());
    let rendered = working.path().join("rendered");
    assert!(rendered.join("SKILL.md").is_file());
    assert!(rendered.join("agents/openai.yaml").is_file());
    let check = Command::new(env!("CARGO_BIN_EXE_worktree"))
        .args(["skill", "--out", "rendered", "--check"])
        .current_dir(working.path())
        .output()
        .expect("run worktree CLI");
    assert!(check.status.success());
}
